#pragma once

#include "Common.h"
#include "HalfEdgeMesh.h"
#include "Mesh.h"
#include <QString>
#include <QTextStream>
#include <memory>
#include <vector>

/**
 * @brief OBJ File Format Handler
 * Handles import and export of Wavefront OBJ files
 */
class OBJFileHandler {
public:
    struct ImportOptions {
        bool mergeVertices = true;
        bool generateNormals = true;
        bool generateTexCoords = false;
        float vertexMergeTolerance = 1e-6f;
    };
    
    struct ExportOptions {
        bool exportNormals = true;
        bool exportTexCoords = true;
        bool exportGroups = false;
        int precision = 6;
    };
    
    struct ImportResult {
        bool success = false;
        QString errorMessage;
        std::vector<MeshPtr> meshes;
        std::vector<QString> meshNames;
        int vertexCount = 0;
        int faceCount = 0;
    };

public:
    // Static import/export methods
    static ImportResult importFromFile(const QString& filePath, const ImportOptions& options = ImportOptions());
    static bool exportToFile(const QString& filePath, MeshPtr mesh, const ExportOptions& options = ExportOptions());
    static bool exportToFile(const QString& filePath, HalfEdgeMeshPtr mesh, const ExportOptions& options = ExportOptions());
    static bool exportToFile(const QString& filePath, const std::vector<MeshPtr>& meshes, const ExportOptions& options = ExportOptions());
    
    // Stream-based operations
    static ImportResult importFromStream(QTextStream& stream, const ImportOptions& options = ImportOptions());
    static bool exportToStream(QTextStream& stream, MeshPtr mesh, const ExportOptions& options = ExportOptions());
    static bool exportToStream(QTextStream& stream, HalfEdgeMeshPtr mesh, const ExportOptions& options = ExportOptions());

private:
    // Internal parsing methods
    static bool parseVertex(const QStringList& tokens, QVector3D& vertex);
    static bool parseNormal(const QStringList& tokens, QVector3D& normal);
    static bool parseTexCoord(const QStringList& tokens, QVector2D& texCoord);
    static bool parseFace(const QStringList& tokens, std::vector<int>& vertexIndices, 
                         std::vector<int>& texCoordIndices, std::vector<int>& normalIndices);
    
    // Mesh building
    static MeshPtr buildMesh(const std::vector<QVector3D>& vertices,
                            const std::vector<QVector3D>& normals,
                            const std::vector<QVector2D>& texCoords,
                            const std::vector<std::vector<int>>& faces,
                            const std::vector<std::vector<int>>& texCoordFaces,
                            const std::vector<std::vector<int>>& normalFaces,
                            const ImportOptions& options);
    
    // Vertex merging
    static void mergeVertices(std::vector<Vertex>& vertices, std::vector<unsigned int>& indices, float tolerance);
    
    // Normal generation
    static void generateNormals(std::vector<Vertex>& vertices, const std::vector<unsigned int>& indices);
    
    // Utility methods
    static QString formatFloat(float value, int precision);
    static int parseIndex(const QString& indexStr, int maxIndex);
};

/**
 * @brief STL File Format Handler
 * Handles import and export of STL files (ASCII and Binary)
 */
class STLFileHandler {
public:
    enum class Format {
        ASCII,
        Binary,
        Auto // Detect automatically
    };
    
    struct ImportOptions {
        Format format = Format::Auto;
        bool mergeVertices = true;
        float vertexMergeTolerance = 1e-6f;
    };
    
    struct ExportOptions {
        Format format = Format::ASCII;
        QString header = "Generated by RudeBase3D";
    };
    
    struct ImportResult {
        bool success = false;
        QString errorMessage;
        MeshPtr mesh;
        int triangleCount = 0;
        Format detectedFormat = Format::ASCII;
    };

public:
    // Static import/export methods
    static ImportResult importFromFile(const QString& filePath, const ImportOptions& options = ImportOptions());
    static bool exportToFile(const QString& filePath, MeshPtr mesh, const ExportOptions& options = ExportOptions());
    static bool exportToFile(const QString& filePath, HalfEdgeMeshPtr mesh, const ExportOptions& options = ExportOptions());

private:
    // Format detection
    static Format detectFormat(const QString& filePath);
    
    // ASCII STL methods
    static ImportResult importASCII(QTextStream& stream, const ImportOptions& options);
    static bool exportASCII(QTextStream& stream, MeshPtr mesh, const ExportOptions& options);
    
    // Binary STL methods
    static ImportResult importBinary(const QString& filePath, const ImportOptions& options);
    static bool exportBinary(const QString& filePath, MeshPtr mesh, const ExportOptions& options);
    
    // Utility methods
    static QVector3D parseVector3(const QStringList& tokens, int startIndex);
};

/**
 * @brief PLY File Format Handler
 * Handles import and export of PLY (Polygon File Format) files
 */
class PLYFileHandler {
public:
    struct ImportOptions {
        bool mergeVertices = false;
        float vertexMergeTolerance = 1e-6f;
    };
    
    struct ExportOptions {
        bool binary = false;
        bool exportNormals = true;
        bool exportColors = true;
    };
    
    struct ImportResult {
        bool success = false;
        QString errorMessage;
        MeshPtr mesh;
        int vertexCount = 0;
        int faceCount = 0;
        bool hasNormals = false;
        bool hasColors = false;
    };

public:
    // Static import/export methods
    static ImportResult importFromFile(const QString& filePath, const ImportOptions& options = ImportOptions());
    static bool exportToFile(const QString& filePath, MeshPtr mesh, const ExportOptions& options = ExportOptions());
    static bool exportToFile(const QString& filePath, HalfEdgeMeshPtr mesh, const ExportOptions& options = ExportOptions());

private:
    // Header parsing
    static bool parseHeader(QTextStream& stream, int& vertexCount, int& faceCount, 
                           bool& hasNormals, bool& hasColors, bool& isBinary);
    
    // Data parsing
    static bool parseVertices(QTextStream& stream, int count, bool hasNormals, bool hasColors, 
                             std::vector<QVector3D>& positions, std::vector<QVector3D>& normals, 
                             std::vector<QVector4D>& colors);
    static bool parseFaces(QTextStream& stream, int count, std::vector<std::vector<int>>& faces);
};

/**
 * @brief File Format Manager
 * Manages all file format handlers and provides a unified interface
 */
class FileFormatManager {
public:
    enum class Format {
        OBJ,
        STL,
        PLY,
        Unknown
    };
    
    struct ImportResult {
        bool success = false;
        QString errorMessage;
        std::vector<MeshPtr> meshes;
        std::vector<QString> meshNames;
        Format detectedFormat = Format::Unknown;
        QString filePath;
    };

public:
    // Format detection
    static Format detectFormat(const QString& filePath);
    static QStringList getSupportedImportExtensions();
    static QStringList getSupportedExportExtensions();
    
    // Unified import/export
    static ImportResult importFile(const QString& filePath);
    static bool exportFile(const QString& filePath, MeshPtr mesh);
    static bool exportFile(const QString& filePath, HalfEdgeMeshPtr mesh);
    static bool exportFile(const QString& filePath, const std::vector<MeshPtr>& meshes);
    
    // Format-specific options
    static void setOBJImportOptions(const OBJFileHandler::ImportOptions& options);
    static void setOBJExportOptions(const OBJFileHandler::ExportOptions& options);
    static void setSTLImportOptions(const STLFileHandler::ImportOptions& options);
    static void setSTLExportOptions(const STLFileHandler::ExportOptions& options);
    static void setPLYImportOptions(const PLYFileHandler::ImportOptions& options);
    static void setPLYExportOptions(const PLYFileHandler::ExportOptions& options);

private:
    static OBJFileHandler::ImportOptions s_objImportOptions;
    static OBJFileHandler::ExportOptions s_objExportOptions;
    static STLFileHandler::ImportOptions s_stlImportOptions;
    static STLFileHandler::ExportOptions s_stlExportOptions;
    static PLYFileHandler::ImportOptions s_plyImportOptions;
    static PLYFileHandler::ExportOptions s_plyExportOptions;
};
